export const CREATE_COMMENT_FAILED = 'CREATE_COMMENT_FAILED';
export const CREATE_COMMENT_LOADING = 'CREATE_COMMENT_LOADING';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';

export const CREATE_POST_FAILED = 'CREATE_POST_FAILED';
export const CREATE_POST_LOADING = 'CREATE_POST_LOADING';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';

export const GET_AUTHOR_FAILED = 'GET_AUTHOR_FAILED';
export const GET_AUTHOR_LOADING = 'GET_AUTHOR_LOADING';
export const GET_AUTHOR_SUCCESS = 'GET_AUTHOR_SUCCESS';

export const GET_COMMENT_FAILED = 'GET_COMMENT_FAILED';
export const GET_COMMENT_LOADING = 'GET_COMMENT_LOADING';
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';

export const GET_POST_FAILED = 'GET_POST_FAILED';
export const GET_POST_LOADING = 'GET_POST_LOADING';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';

export const GET_SINGLE_AUTHOR_FAILED = 'GET_SINGLE_AUTHOR_FAILED';
export const GET_SINGLE_AUTHOR_LOADING = 'GET_SINGLE_AUTHOR_LOADING';
export const GET_SINGLE_AUTHOR_SUCCESS = 'GET_SINGLE_AUTHOR_SUCCESS';

export const GET_SINGLE_POST_FAILED = 'GET_SINGLE_POST_FAILED';
export const GET_SINGLE_POST_LOADING = 'GET_SINGLE_POST_LOADING';
export const GET_SINGLE_POST_SUCCESS = 'GET_SINGLE_POST_SUCCESS';
